vim.keymap.set('i', 'jk', '<esc>')
vim.keymap.set('n', '<right>', 'gT')
vim.keymap.set('n', '<left>', 'gt')
vim.keymap.set('n', '<up>', '<C-u>')
vim.keymap.set('n', '<down>', '<C-d>')
vim.keymap.set('n', '<leader><space>', '<C-^>`"zz')
vim.keymap.set('n', 'U', '<c-r>')
vim.keymap.set({ 'n', 'v' }, ';', ':')

--  terminal setting
vim.keymap.set('n', '<leader>=', '<C-w>=', { desc = 'Resize all windows to be equal' })
vim.keymap.set('t', 'jk', '<C-\\><C-n>')
vim.keymap.set('t', '<esc>', '<C-\\><C-n>')
vim.keymap.set('t', '<C-j>', '<C-\\><C-n><C-w>j')
vim.keymap.set('t', '<C-k>', '<C-\\><C-n><C-w>k')
vim.keymap.set('t', '<C-h>', '<C-\\><C-n><C-w>h')
vim.keymap.set('t', '<C-l>', '<C-\\><C-n><C-w>l')
vim.keymap.set('n', 'so', '<C-w>o')
vim.keymap.set('n', 'sh', '<C-w>h')
vim.keymap.set('n', 'sk', '<C-w>k')
vim.keymap.set('n', 'sj', '<C-w>j')
vim.keymap.set('n', 'sl', '<C-w>l')
vim.keymap.set('n', 'tt', ':tab term<cr>')
vim.keymap.set('n', 'tx', ':term<cr>')
vim.keymap.set('n', 'tv', ':vert term<cr>')
vim.keymap.set('n', 'st', function()
  vim.cmd.new()
  vim.cmd.wincmd 'J'
  vim.api.nvim_win_set_height(0, 12)
  vim.wo.winfixheight = true
  vim.cmd.term()
end)
